## Model Training

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


In [2]:
df = pd.read_csv('data/cleaned_career_dataset_20k.csv')
df.head()

,experience_years,projects_count,target_career,adobe xd,ads,agile,android,ansible,aws,azure,...,dominant_project_domain_cloud,dominant_project_domain_data,dominant_project_domain_design,dominant_project_domain_devops,dominant_project_domain_marketing,dominant_project_domain_ml,dominant_project_domain_mobile,dominant_project_domain_none,dominant_project_domain_security,dominant_project_domain_web
0,2,3,4,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,4,6,0,0,0,0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,3,5,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,3,11,0,0,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3,5,4,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [3]:
X = df.drop('target_career', axis=1)
y = df['target_career']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(probability=True),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

In [4]:
def evaluate_model(y_test, y_pred):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1_scr = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    return accuracy, precision, recall, f1_scr, cm

In [5]:
model_list = []
accuracy_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_acc, model_train_precision, model_train_recall, model_train_f1, model_train_cm = evaluate_model(y_train, y_train_pred)
    model_test_acc, model_test_precision, model_test_recall, model_test_f1, model_test_cm = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("Model Performance on Train Dataset:")
    print(f"Accuracy: {model_train_acc}")
    print(f"Precision: {model_train_precision}")
    print(f"Recall: {model_train_recall}")
    print(f"F1-Score: {model_train_f1}")
    print("Confusion Matrix:")
    print(model_train_cm)

    print('-'*50)

    print("\nModel Performance on Test Dataset:")
    print(f"Accuracy: {model_test_acc}")
    print(f"Precision: {model_test_precision}")
    print(f"Recall: {model_test_recall}")
    print(f"F1-Score: {model_test_f1}")
    print("Confusion Matrix:")
    print(model_test_cm)

    accuracy_list.append(model_test_acc)
    print('='*50)
    print('\n')

Logistic Regression
Model Performance on Train Dataset:
Accuracy: 0.9932639722555688
Precision: 0.9932770534676506
Recall: 0.9932639722555688
F1-Score: 0.9932646626385244
Confusion Matrix:
[[1061    0    0    0    0    0    0    0    2    0    0    0    0    0]
 [   0 1124    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0 1049    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0  984    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0  996   32    0    0    0    0    0    0    0    0]
 [   0    0    0    0   45 1014    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1064    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0 1118    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0 1129    0    0    0    0    8]
 [   0    0    0    0    0    0    0    0    0 1061    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0 1076    0    0    0]
 [   0  

e:\Kaushal AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


AdaBoost
Model Performance on Train Dataset:
Accuracy: 0.6746698679471789
Precision: 0.6826706616969342
Recall: 0.6746698679471789
F1-Score: 0.6259233380852369
Confusion Matrix:
[[   1    0    0    0    0    0    0    0  996    0    0   66    0    0]
 [   0    2    0    0    0    0    0    0    0    0    0 1122    0    0]
 [   0   39 1005    0    0    0    0    0    0    0    0    5    0    0]
 [   0    0    0  982    0    0    0    0    0    0    0    2    0    0]
 [   0    0    0    0  956    5    0    0    0    0    0   67    0    0]
 [   0    0    0    0 1023    6    0    0    0    0    0   30    0    0]
 [   0    6    0    0    0    0 1030    0    0    0    0   28    0    0]
 [   0    1    0    0    0    0    0  840    0    0    0  277    0    0]
 [   1    0    0    0    0    0    0    0  799    0    0   80    0  258]
 [   0    0    0    0    0    0    0    0    0 1032    0   29    0    0]
 [   0    1    0    0    0    0    0    0    0    0  979   96    0    0]
 [   0    7    0   

e:\Kaushal AI\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [13:51:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBoost
Model Performance on Train Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
Confusion Matrix:
[[1063    0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0 1124    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0 1049    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0  984    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0 1028    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 1059    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1064    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0 1118    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0 1138    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0 1061    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0 1076    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0 1094    0    0]
 [   0 

In [6]:
accuracy_df = pd.DataFrame(list(zip(model_list, accuracy_list)), columns=['Model', 'Accuracy Score']).sort_values(by='Accuracy Score', ascending=False)

In [7]:
accuracy_df

,Model,Accuracy Score
2,Random Forest,0.991196
0,Logistic Regression,0.990996
7,XGBoost,0.990796
3,Gradient Boosting,0.990396
6,SVM,0.989996
1,Decision Tree,0.974790
5,KNN,0.964586
4,AdaBoost,0.679872


In [8]:
# Save Random Forest model
import joblib
rf_model = RandomForestClassifier()
rf_model.fit(X, y)
joblib.dump(rf_model, 'demo_artifacts/rf_model.pkl')
print("Random Forest model saved successfully!")


Random Forest model saved successfully!
